obj-m += entry.o

entry-objs := \
	entry.o \
	command.o \
	memory.o \
	memory_safe.o \
	memory_batch.o \
	process.o \
	process_cache.o \
	touch.o \
	hook.o \
	stealth.o \
	auth.o \
	antidbg.o \
	file_hide.o \
	proc_hide.o
